language: go

go:
  - 1.11.x

before_install:
  # Build tools
  - go get golang.org/x/lint/golint
  - go get github.com/gordonklaus/ineffassign

  # Project dependencies
  - go get github.com/djherbis/times
  - go get github.com/mitchellh/go-homedir       
  - go get github.com/spf13/viper
  - go get github.com/theckman/go-flock
  - go get gopkg.in/gomail.v2

script:
  - make test

  # run tests on a standard platform
  - go test -v ./... -coverprofile=coverage.txt -covermode=atomic
  - go test -v ./... -race

after_success:
  # Upload coverage results to codecov.io
  - bash <(curl -s https://codecov.io/bash)
